[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html"]

[serve]
address = "127.0.0.1"
port = 8080

[[proxy]]
backend = "http://127.0.0.1:3001/v1"
rewrite = "/v1"

[[proxy]]
backend = "http://127.0.0.1:3001/health"
rewrite = "/health"
